<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<OutputPath>C:\Users\Lucas\Documents\Projects\fivem\code\bin\server\windows\debug\citizen\dotnet</OutputPath>
		<BaseOutputPath>C:\Users\Lucas\Documents\Projects\fivem\code\bin\server\windows\debug\citizen\dotnet</BaseOutputPath>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>

</Project>
